
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      
    - name: Build and test CI_macOS Scheme
      run: xcodebuild clean build test -project ${GITHUB_WORKSPACE}/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      
    - name: Build and test CI_iOS Scheme
      run: xcodebuild clean build test -workspace ${GITHUB_WORKSPACE}/EssentialApp.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES MACOSX_DEPLOYMENT_TARGET=12.6.3
